# Generated by Django 2.2.1 on 2019-05-13 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpnm_id', models.CharField(max_length=500)),
                ('mapbox_id', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=1000)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('iso_3166_1', models.CharField(blank=True, max_length=50, null=True)),
                ('iso_3166_2', models.CharField(blank=True, max_length=50, null=True)),
                ('place_class', models.CharField(blank=True, max_length=200, null=True)),
                ('place_type', models.CharField(blank=True, max_length=200, null=True)),
                ('geo_type', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('favorited', models.PositiveIntegerField(blank=True, null=True)),
                ('favorited_by', models.CharField(blank=True, max_length=200, null=True)),
                ('reported', models.CharField(blank=True, max_length=200, null=True)),
                ('reported_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('iso_639_3', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('in_language', models.CharField(max_length=200)),
                ('from_language', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('endonym', models.NullBooleanField()),
                ('reference', models.CharField(blank=True, max_length=2500, null=True)),
                ('reference_url', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('derived_term', models.CharField(blank=True, max_length=200, null=True)),
                ('derived_url', models.URLField(blank=True, null=True)),
                ('see_also_title', models.CharField(blank=True, max_length=200, null=True)),
                ('see_also_link', models.URLField(blank=True, null=True)),
                ('username', models.CharField(max_length=200)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tpnm.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('reported', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tpnm.Article')),
            ],
        ),
    ]
