# Generated by Django 2.2 on 2019-05-03 21:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_by', models.CharField(max_length=50)),
                ('created', models.DateField(auto_now_add=True)),
                ('edited', models.DateField(auto_now=True)),
                ('favorite', models.PositiveSmallIntegerField()),
                ('reported', models.CharField(max_length=200)),
                ('reported_by', models.CharField(max_length=200)),
            ],
        ),
    ]
