# Generated by Django 2.2 on 2019-05-06 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tpnm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iso_639_3', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='favorite',
            new_name='favorited',
        ),
        migrations.AddField(
            model_name='articles',
            name='edited_by',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='favorited_by',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Edits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('in_language', models.CharField(max_length=3)),
                ('from_language', models.CharField(max_length=3)),
                ('content', models.TextField()),
                ('reference', models.CharField(max_length=2500)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('derived_term', models.CharField(max_length=200)),
                ('derived_url', models.URLField()),
                ('see_also_title', models.CharField(max_length=200)),
                ('see_also_link', models.URLField()),
                ('username', models.CharField(max_length=200)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tpnm.Articles')),
            ],
        ),
    ]
