# Generated by Django 2.2.1 on 2019-05-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tpnm', '0002_auto_20190514_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='named_id',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
