# Generated by Django 2.2 on 2019-05-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tpnm', '0002_auto_20190506_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='edited_by',
        ),
        migrations.AddField(
            model_name='talk',
            name='reported',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='favorited',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='favorited_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='reported',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='reported_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='edits',
            name='derived_term',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='edits',
            name='derived_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edits',
            name='from_language',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='edits',
            name='in_language',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='edits',
            name='reference',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='edits',
            name='see_also_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edits',
            name='see_also_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
