# Generated by Django 2.2 on 2019-05-06 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tpnm', '0003_auto_20190506_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_language', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=2500, null=True)),
                ('reference_url', models.URLField(blank=True, null=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('derived_term', models.CharField(blank=True, max_length=200, null=True)),
                ('derived_url', models.URLField(blank=True, null=True)),
                ('see_also_title', models.CharField(blank=True, max_length=200, null=True)),
                ('see_also_link', models.URLField(blank=True, null=True)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Talk',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
        migrations.RenameModel(
            old_name='Languages',
            new_name='Language',
        ),
        migrations.DeleteModel(
            name='Edits',
        ),
        migrations.AddField(
            model_name='edit',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tpnm.Article'),
        ),
        migrations.AddField(
            model_name='edit',
            name='in_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tpnm.Language'),
        ),
    ]
