# Generated by Django 2.2.1 on 2019-05-15 18:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tpnm', '0004_auto_20190515_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='from_language',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=3), blank=True, default=list, null=True, size=5),
        ),
    ]
