# Generated by Django 2.2 on 2019-05-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tpnm', '0004_auto_20190506_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='family_code',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='father_code',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='status',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
