# Generated by Django 2.2 on 2019-05-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tpnm', '0005_auto_20190506_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='family_code',
            new_name='family_id',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='father_code',
            new_name='father_id',
        ),
        migrations.RemoveField(
            model_name='language',
            name='code',
        ),
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
