# Generated by Django 2.2.1 on 2019-05-16 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tpnm', '0006_auto_20190516_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edit',
            old_name='see_also_link',
            new_name='see_also_url',
        ),
    ]
