# Generated by Django 2.2 on 2019-05-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tpnm', '0007_auto_20190507_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='family_id',
        ),
        migrations.RemoveField(
            model_name='language',
            name='father_id',
        ),
        migrations.RemoveField(
            model_name='language',
            name='status',
        ),
        migrations.AddField(
            model_name='language',
            name='glottocode',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='macroarea',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
