# Generated by Django 2.2.1 on 2019-05-16 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tpnm', '0007_auto_20190516_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='app_tpnm.Article'),
        ),
    ]
