# Generated by Django 2.2.1 on 2019-05-18 23:23

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tpnm', '0008_auto_20190516_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edit',
            name='reference_url',
        ),
        migrations.RemoveField(
            model_name='edit',
            name='see_also_title',
        ),
        migrations.RemoveField(
            model_name='edit',
            name='see_also_url',
        ),
        migrations.AddField(
            model_name='edit',
            name='see_also',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True), blank=True, default=list, null=True, size=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='app_tpnm.Comment'),
        ),
        migrations.AlterField(
            model_name='edit',
            name='from_language',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=3), blank=True, default=list, null=True, size=50),
        ),
        migrations.AlterField(
            model_name='edit',
            name='in_language',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=3), blank=True, default=list, null=True, size=250),
        ),
        migrations.AlterField(
            model_name='edit',
            name='reference',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True), blank=True, default=list, null=True, size=50),
        ),
    ]
