# Generated by Django 2.2.1 on 2019-05-19 00:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tpnm', '0009_auto_20190518_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='from_language',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), blank=True, default=list, null=True, size=50),
        ),
        migrations.AlterField(
            model_name='edit',
            name='in_language',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), blank=True, default=list, null=True, size=250),
        ),
        migrations.AlterField(
            model_name='edit',
            name='reference',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), blank=True, default=list, null=True, size=50),
        ),
        migrations.AlterField(
            model_name='edit',
            name='see_also',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), blank=True, default=list, null=True, size=50),
        ),
    ]
