# Generated by Django 2.2 on 2019-05-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tpnm', '0010_auto_20190507_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
    ]
