# Generated by Django 2.2.1 on 2019-05-20 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tpnm', '0011_auto_20190520_2054'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articlename',
            unique_together={('tpnm_id', 'name')},
        ),
    ]
