# Generated by Django 2.2 on 2019-05-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tpnm', '0011_remove_article_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='data',
        ),
    ]
