# Generated by Django 2.2 on 2019-05-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tpnm', '0012_remove_article_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
