# Generated by Django 2.2.1 on 2019-05-11 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tpnm', '0013_article_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edit',
            name='in_language',
        ),
        migrations.RemoveField(
            model_name='language',
            name='glottocode',
        ),
        migrations.RemoveField(
            model_name='language',
            name='macroarea',
        ),
    ]
