# Generated by Django 6.0.7 on 2026-07-12 07:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('wikidata_qid', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('osm_type', models.CharField(blank=True, max_length=8, null=True)),
                ('osm_id', models.BigIntegerField(blank=True, null=True)),
                ('anchor_level', models.CharField(choices=[('wikidata', 'Wikidata'), ('osm', 'Osm'), ('name', 'Name')], max_length=8)),
                ('display_name', models.CharField(max_length=255)),
                ('feature_class', models.CharField(max_length=40)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, geography=True, null=True, srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('bbox', django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('osm_id__isnull', False)), fields=('osm_type', 'osm_id'), name='unique_osm_element')],
            },
        ),
    ]
