# Generated by Django 6.0.7 on 2026-07-12 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protection_level', models.CharField(choices=[('none', 'None'), ('registered', 'Registered'), ('admin', 'Admin')], default='none', max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='core.place')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('content', models.JSONField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-id'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.revision'),
        ),
        migrations.CreateModel(
            name='PlaceName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, max_length=16)),
                ('is_endonym', models.BooleanField(default=False)),
                ('from_languages', models.JSONField(blank=True, default=list)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='core.place')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='core_placen_name_b6a53f_idx')],
                'constraints': [models.UniqueConstraint(fields=('place', 'name', 'language'), name='unique_place_name_language')],
            },
        ),
    ]
