# Generated by Django 6.0.7 on 2026-07-12 16:55

import django.contrib.gis.db.models.fields
from django.db import migrations


def backfill_label_points(apps, schema_editor):
    """Pre-label_point places: snap onto the cached geometry where one
    exists (point_on_surface lies on the feature); otherwise leave null
    and let the API fall back to the centroid."""
    Place = apps.get_model('core', 'Place')
    for place in Place.objects.exclude(geometry=None):
        geometry = place.geometry
        place.label_point = (
            geometry if geometry.geom_type == 'Point'
            else geometry.point_on_surface
        )
        place.save(update_fields=['label_point'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_article_revision_article_current_revision_placename'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='label_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.RunPython(
            backfill_label_points, migrations.RunPython.noop
        ),
    ]
