# Generated by Django 6.0.7 on 2026-07-14 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_talkpost_deleted_talkpost_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='suppressed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='suppressed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
