# Generated by Django 6.0.7 on 2026-07-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_report_category_ban_modaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modaction',
            name='action',
            field=models.CharField(choices=[('delete_post', 'Delete Post'), ('restore_post', 'Restore Post'), ('suppress_revision', 'Suppress Revision'), ('restore_revision', 'Restore Revision'), ('delete_thread', 'Delete Thread'), ('ban_user', 'Ban User'), ('unban_user', 'Unban User'), ('promote_mod', 'Promote Mod'), ('demote_mod', 'Demote Mod'), ('resolve_report', 'Resolve Report'), ('dismiss_report', 'Dismiss Report')], max_length=24),
        ),
    ]
