# Generated by Django 6.0.7 on 2026-07-15 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_modaction_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modaction',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.article'),
        ),
        migrations.AlterField(
            model_name='modaction',
            name='action',
            field=models.CharField(choices=[('delete_post', 'Delete Post'), ('restore_post', 'Restore Post'), ('suppress_revision', 'Suppress Revision'), ('restore_revision', 'Restore Revision'), ('delete_thread', 'Delete Thread'), ('delete_article', 'Delete Article'), ('restore_article', 'Restore Article'), ('revert_article', 'Revert Article'), ('ban_user', 'Ban User'), ('unban_user', 'Unban User'), ('promote_mod', 'Promote Mod'), ('demote_mod', 'Demote Mod'), ('resolve_report', 'Resolve Report'), ('dismiss_report', 'Dismiss Report')], max_length=24),
        ),
    ]
