# Generated by Django 6.0.7 on 2026-07-22 06:56

import django.db.models.deletion
from django.db import migrations, models


def backfill_canonical_slugs(apps, schema_editor):
    """Every existing Place gets one canonical PlaceSlug mirroring its slug."""
    Place = apps.get_model('core', 'Place')
    PlaceSlug = apps.get_model('core', 'PlaceSlug')
    PlaceSlug.objects.bulk_create(
        PlaceSlug(place=place, slug=place.slug, is_canonical=True)
        for place in Place.objects.all()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_article_deleted_article_deleted_by_modaction_article_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceSlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('is_canonical', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slugs', to='core.place')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_canonical', True)), fields=('place',), name='one_canonical_slug_per_place')],
            },
        ),
        migrations.RunPython(
            backfill_canonical_slugs, migrations.RunPython.noop
        ),
    ]
