# Generated by Django 6.0.7 on 2026-08-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_termsacceptance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('spam', 'Spam'), ('vandalism', 'Vandalism'), ('harassment', 'Harassment'), ('personal_info', 'Personal Info'), ('copyright', 'Copyright'), ('other', 'Other')], default='other', max_length=16),
        ),
    ]
