# Generated by Django 6.1 on 2026-08-17 20:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_modaction_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision', models.CharField(max_length=120)),
                ('subdivision_local', models.CharField(blank=True, max_length=120)),
                ('subdivision_type', models.CharField(blank=True, max_length=60)),
                ('country', models.CharField(max_length=120)),
                ('country_a3', models.CharField(blank=True, max_length=8)),
                ('country_iso', models.CharField(blank=True, max_length=8)),
                ('subdivision_iso', models.CharField(blank=True, max_length=16)),
                ('wikidata_qid', models.CharField(blank=True, max_length=32)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'indexes': [models.Index(fields=['subdivision'], name='core_admina_subdivi_f72e33_idx'), models.Index(fields=['country'], name='core_admina_country_d5a857_idx')],
            },
        ),
    ]
