# Generated by Django 6.1 on 2026-08-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_adminarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='placeslug',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
