# Generated by Django 6.1 on 2026-08-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_place_slug_alter_placeslug_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='admin_country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='place',
            name='admin_country_iso',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='place',
            name='admin_subdivision',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='place',
            name='admin_subdivision_iso',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
