"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# The Vite build Django serves in production: core/spa.py renders
# index.html (injecting per-place SEO meta), WhiteNoise serves the rest.
WEB_DIST = Path(os.environ.get('DJANGO_WEB_DIST', BASE_DIR.parent / 'web' / 'dist'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-dev-only-vp2m4vt^1nq(u+kj#f&yl@8s!z0hw6r$3xebc9do7ga5i_',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1'

ALLOWED_HOSTS = [
    h for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h
]

# The Vite dev/preview proxy forwards to :8000 with the browser's Origin
# intact, so those origins must be trusted for CSRF checks in dev.
CSRF_TRUSTED_ORIGINS = [
    o
    for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if o
]
if DEBUG:
    CSRF_TRUSTED_ORIGINS += [
        'http://localhost:5173',
        'http://localhost:4173',
    ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'rest_framework',
    'allauth',
    'allauth.account',
    'allauth.headless',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Defaults match the PostGIS service in docker-compose.yml.
# GeoDjango needs system GDAL/GEOS (dnf: gdal geos, apt: gdal-bin libgdal-dev
# libgeos-dev).
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ.get('POSTGRES_DB', 'toponymia'),
        'USER': os.environ.get('POSTGRES_USER', 'toponymia'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'toponymia'),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Authentication — django-allauth in headless-only mode: the React SPA
# talks JSON to /_allauth/browser/v1/* using the session cookie.

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Email is required and must be verified before an account is usable — the
# anti-spam floor, since re-registration is otherwise free and instant.
# Verification is by short code (not a link): allauth emails a code and the
# headless signup flow stays pending until the SPA posts it back, so there is
# no email-link route to catch and the user never leaves the signup form.
ACCOUNT_LOGIN_METHODS = {'username'}
ACCOUNT_SIGNUP_FIELDS = ['username*', 'email*', 'password1*']
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_VERIFICATION_BY_CODE_ENABLED = True
ACCOUNT_UNIQUE_EMAIL = True
HEADLESS_ONLY = True
HEADLESS_CLIENTS = ('browser',)


# Email — verification codes now, password reset later. Dev defaults to the
# console backend so signup works with no SMTP configured (the code prints to
# the runserver console); production points DJANGO_EMAIL_BACKEND at SMTP and
# fills host/credentials from the environment. Plain SMTP, no transactional
# API key — keeps to the project's keyless rule.
EMAIL_BACKEND = os.environ.get(
    'DJANGO_EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.environ.get('DJANGO_EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.environ.get('DJANGO_EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('DJANGO_EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('DJANGO_EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('DJANGO_EMAIL_USE_TLS', '1') == '1'
DEFAULT_FROM_EMAIL = os.environ.get(
    'DJANGO_DEFAULT_FROM_EMAIL', 'Toponymia <noreply@toponymia.org>'
)


# DRF — simple rate limits on anonymous-facing / expensive endpoints
#. UserRateThrottle keys by user id when logged in, client
# IP otherwise, so the per-endpoint scopes below cover both. The default
# cache (LocMemCache) is per-process — fine for a single-VPS v1; a shared
# cache (Redis) is the upgrade if we ever run multiple workers.
REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '120/min',
        'user': '600/min',
        'resolve': '30/min',
        'write': '40/min',
        'report': '15/min',
        'talk': '40/min',
    },
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # collectstatic target (admin assets)

# WhiteNoise serves the Vite build at the site root. Everything under
# /assets/ is content-hashed by Vite, so browsers may cache it forever.
WHITENOISE_ROOT = WEB_DIST


def immutable_file_test(path, url):
    return url.startswith('/assets/')


WHITENOISE_IMMUTABLE_FILE_TEST = immutable_file_test


# Production hardening — active whenever DEBUG is off. TLS terminates at
# the reverse proxy (Caddy/nginx), which must send X-Forwarded-Proto;
# HSTS is left to the proxy config.
if not DEBUG:
    if SECRET_KEY.startswith('django-insecure-'):
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY must be set when DJANGO_DEBUG=0'
        )
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
