"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from django.utils.csp import CSP

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# The Vite build Django serves in production: core/spa.py renders
# index.html (injecting per-place SEO meta), WhiteNoise serves the rest.
WEB_DIST = Path(os.environ.get('DJANGO_WEB_DIST', BASE_DIR.parent / 'web' / 'dist'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-dev-only-vp2m4vt^1nq(u+kj#f&yl@8s!z0hw6r$3xebc9do7ga5i_',
)

# SECURITY WARNING: don't run with debug turned on in production!
#
# This defaults to OFF so that a forgotten variable in production fails safe:
# an unset DJANGO_DEBUG gives a hardened server, not tracebacks-with-settings
# on every error page. It also keeps the SECRET_KEY guard below live, since
# that guard only runs when DEBUG is off — with a permissive default, one
# forgotten variable disabled both protections at once.
#
# Development doesn't need to set anything: manage.py (the dev entry point)
# defaults it to '1'. gunicorn imports config.wsgi and never runs manage.py,
# so production keeps the safe default unless it opts in explicitly.
DEBUG = os.environ.get('DJANGO_DEBUG', '0') == '1'

ALLOWED_HOSTS = [
    h for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h
]

# The Vite dev/preview proxy forwards to :8000 with the browser's Origin
# intact, so those origins must be trusted for CSRF checks in dev.
CSRF_TRUSTED_ORIGINS = [
    o
    for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if o
]
if DEBUG:
    CSRF_TRUSTED_ORIGINS += [
        'http://localhost:5173',
        'http://localhost:4173',
    ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'rest_framework',
    'allauth',
    'allauth.account',
    'allauth.headless',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Before WhiteNoise so static responses carry the policy too, and early
    # enough that request.csp_nonce exists for every view (core/spa.py uses
    # it). Django 6 ships this; no third-party CSP package needed.
    'django.middleware.csp.ContentSecurityPolicyMiddleware',
    # Subclassed to keep the SPA shell out of WhiteNoise's hands — see
    # core/statics.py. Everything else about it is stock.
    'core.statics.ShellExcludedWhiteNoise',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Searched before APP_DIRS, which is the point: the only templates
        # here override allauth's, and 'core' sits after 'allauth' in
        # INSTALLED_APPS, so an app-level copy would lose. See
        # templates/account/email/base_message.txt.
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Defaults match the PostGIS service in docker-compose.yml.
# GeoDjango needs system GDAL/GEOS (dnf: gdal geos, apt: gdal-bin libgdal-dev
# libgeos-dev).
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ.get('POSTGRES_DB', 'toponymia'),
        'USER': os.environ.get('POSTGRES_USER', 'toponymia'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'toponymia'),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Authentication — django-allauth in headless-only mode: the React SPA
# talks JSON to /_allauth/browser/v1/* using the session cookie.

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Email is required and must be verified before an account is usable — the
# anti-spam floor, since re-registration is otherwise free and instant.
# Verification is by short code (not a link): allauth emails a code and the
# headless signup flow stays pending until the SPA posts it back, so there is
# no email-link route to catch and the user never leaves the signup form.
# Log in with either identifier, from one field. Email is what people
# actually remember, so this removes "I forgot my username" as a way to lose
# access — but username keeps working, which is the point: with no
# account-settings page yet there is no way to change your address, so email
# must not be the *only* key to the account. The username is the public
# identity regardless (bylines, talk, history), so signup collects both.
# allauth wants exactly one of its credential keys posted, so the SPA picks by
# looking for an "@" — see ACCOUNT_USERNAME_VALIDATORS below, which is what
# makes that test unambiguous.
# Custom adapter enforces the registration blocklist: a banned account's email
# addresses are recorded in BannedEmail, and this refuses a signup that reuses
# one (see core/adapter.py, core.moderation.block_user_emails).
ACCOUNT_ADAPTER = 'core.adapter.AccountAdapter'
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_USERNAME_VALIDATORS = 'core.validators.username_validators'
ACCOUNT_SIGNUP_FIELDS = ['username*', 'email*', 'password1*']
# Adds the required Terms-of-Use checkbox to signup and records the
# acceptance (core/forms.py). Server-side, so the agreement holds for
# direct API calls too, not just the React form.
ACCOUNT_SIGNUP_FORM_CLASS = 'core.forms.TermsSignupForm'
# Subjects otherwise take allauth's default prefix of "[<site name>] ", and
# with contrib.sites absent the site name is the request host — so every
# subject line read "[www.toponymia.org] ...". Same reasoning as the body
# override in templates/account/email/base_message.txt.
ACCOUNT_EMAIL_SUBJECT_PREFIX = '[Toponymia] '
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_VERIFICATION_BY_CODE_ENABLED = True
ACCOUNT_UNIQUE_EMAIL = True
# One address per account, replaced rather than accumulated: email here is a
# credential (login identifier, reset target), not a list to manage. Adding an
# address supersedes the old one once the new one is verified.
ACCOUNT_CHANGE_EMAIL = True
HEADLESS_ONLY = True
HEADLESS_CLIENTS = ('browser',)

# Password reset by code, for the same reason signup verification is: no
# email-link route to catch, so the whole flow stays inside the auth form and
# needs no SPA route of its own. Login stays username-only while there is no
# account-settings page — losing access to your email must cost you the reset
# path, not the account. allauth's 3-minute default is far too tight for an
# email round trip; 15 minutes is still short enough to bound a leaked code.
ACCOUNT_PASSWORD_RESET_BY_CODE_ENABLED = True
ACCOUNT_PASSWORD_RESET_BY_CODE_TIMEOUT = 15 * 60

# Required by the two enumeration-resistant flows, and *only* by them. Both
# work the same way: the request that would reveal whether an account exists
# sends mail instead of erroring, and that mail needs a link into the SPA.
# HEADLESS_ONLY raises ImproperlyConfigured rather than defaulting, so a
# missing key here is a 500 on the exact path nobody tests by hand.
#
# - `account_signup` — a reset requested for an address with no account still
#   sends mail ("someone asked to reset a password here; you have no
#   account"), and that mail links to signup.
# - `account_reset_password` — the mirror case, and the one that was missing
#   until 2026-08-09: signing up with an address that *already* has an account
#   sends "you already have an account" instead of admitting the address is
#   taken, and that mail links to the reset flow. Every signup by a returning
#   user who forgot they had an account hit a 500 without it.
#
# Neither is a route: auth is a header popover, and only /terms and /privacy
# are real paths. So the site root is the honest target for both; relative
# URLs are made absolute against the request.
#
# allauth asks for two further keys, `account_reset_password_from_key` and
# `account_confirm_email`, on its *by-link* flows only. Both are unreachable
# while the two ACCOUNT_*_BY_CODE_ENABLED settings above are on — but turning
# either off reintroduces exactly the 500 described here, on a path that only
# real users walk. Add the key in the same commit if that ever changes.
HEADLESS_FRONTEND_URLS = {
    'account_signup': '/',
    'account_reset_password': '/',
}


# Email — verification and password-reset codes. Dev defaults to the
# console backend so signup works with no SMTP configured (the code prints to
# the runserver console); production points DJANGO_EMAIL_BACKEND at SMTP and
# fills host/credentials from the environment. Plain SMTP, no transactional
# API key — keeps to the project's keyless rule.
EMAIL_BACKEND = os.environ.get(
    'DJANGO_EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.environ.get('DJANGO_EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.environ.get('DJANGO_EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('DJANGO_EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('DJANGO_EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('DJANGO_EMAIL_USE_TLS', '1') == '1'
DEFAULT_FROM_EMAIL = os.environ.get(
    'DJANGO_DEFAULT_FROM_EMAIL', 'Toponymia <noreply@toponymia.org>'
)


# Signup rate limit — the anti-spam floor alongside mandatory verification.
# allauth's limits are transient and cache-keyed by IP, so *no IP is stored*
# and there is no privacy-policy burden. Its generous defaults already cover
# login, password reset, and code confirmation; we only tighten signup
# (default 20/min/IP) to 10/min/IP — enough to hobble scripted
# mass-registration from one address, generous enough never to bother a real
# user (even a shared campus/office NAT). One rate only: allauth keys the
# limit on action+scope with no duration in the key, so two same-scope rates
# (e.g. a second '/h/ip') would share one bucket and miscount — its own
# defaults only ever combine *different* scopes (ip + key).
ACCOUNT_RATE_LIMITS = {
    'signup': '10/m/ip',
}

# Behind the M11 reverse proxy every request's REMOTE_ADDR is the proxy's own
# IP, which would collapse all users into a single rate-limit bucket. allauth
# recovers the real client IP from X-Forwarded-For by *counting* trusted hops
# (not by trusting the header, which a client can spoof to rotate IPs), so set
# this to the number of proxies in front of Django in production. 0 in dev
# means REMOTE_ADDR is used directly.
ALLAUTH_TRUSTED_PROXY_COUNT = int(
    os.environ.get('DJANGO_TRUSTED_PROXY_COUNT', '0')
)


# Where throttle counters live. LocMemCache is per-process, so with
# `--workers N` every limit below is really N buckets of the stated rate (and
# all of them reset on restart). DJANGO_REDIS_URL points them at one shared
# store instead; unset — which is every dev machine — keeps the in-memory
# default so nothing new has to be running locally.
#
# Redis belongs *on the box*, not in ElastiCache: the only thing that needs to
# share these counters is the gunicorn workers of a single instance, which a
# unix socket does for free. A managed node would cost about as much as the
# instance and add a network partition as a new way to fail. It becomes the
# right answer the day there is more than one app instance to span.
REDIS_URL = os.environ.get('DJANGO_REDIS_URL', '')
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }

# DRF — simple rate limits on anonymous-facing / expensive endpoints
#. UserRateThrottle keys by user id when logged in, client
# IP otherwise, so the per-endpoint scopes below cover both.
#
# NUM_PROXIES is the same trusted-hop count as ALLAUTH_TRUSTED_PROXY_COUNT
# above, and matters for the same reason. Left unset, DRF uses the *whole*
# X-Forwarded-For header as the client identity whenever one is present — so a
# client that sends a different XFF on every request gets a fresh bucket every
# time and is not throttled at all. Behind a proxy that is worse, not better:
# Caddy, ALB and CloudFront all *append* to XFF rather than replacing it, so
# the spoofed prefix survives. Setting the count makes DRF read the Nth entry
# from the right, which only a proxy we trust can have written. 0 in dev means
# REMOTE_ADDR is used and the header is ignored entirely.
REST_FRAMEWORK = {
    'NUM_PROXIES': ALLAUTH_TRUSTED_PROXY_COUNT,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '120/min',
        'user': '600/min',
        'resolve': '30/min',
        'write': '40/min',
        'report': '15/min',
        'talk': '40/min',
    },
}

# Request-body ceiling, stated explicitly rather than inherited. This is the
# outer backstop behind core.serializers' per-field limits: a fully maxed-out
# article snapshot (20 names x 10k etymology + 30 references each, plus
# derivations and see_also) is roughly 900 kB of text, so 2.5 MB leaves room
# for JSON escaping and multi-byte UTF-8 while still bounding what an
# oversized request can force the server to buffer and parse.
DATA_UPLOAD_MAX_MEMORY_SIZE = 2_621_440  # 2.5 MB


# Logging — application exceptions, which nothing else reports.
#
# This exists because Django's default configuration loses them exactly when
# they matter. DEFAULT_LOGGING gives the 'django' logger two handlers:
# 'console', filtered by require_debug_true, and 'mail_admins', filtered by
# require_debug_false. With DEBUG off and ADMINS unset — which is production —
# the first is filtered out and the second has nowhere to send, so an
# unhandled 500 raises, returns a generic error page, and leaves *no trace on
# the server at all*. The user sees a broken page and leaves; you never learn.
#
# So: always log to stderr, unconditionally, with no debug filter. gunicorn
# captures stderr into its error log, so a deployment that configures nothing
# else still records its own exceptions. DJANGO_LOG_DIR additionally writes
# them to a rotating file for a log shipper to tail — self-rotating rather
# than relying on external logrotate, because unbounded logs share the root
# volume with Postgres and a full disk takes down the database.
#
# Deliberately kept to the standard library: no vendor, no key, nothing to
# expire, consistent with the rest of the project's dependencies.
LOG_DIR = os.environ.get('DJANGO_LOG_DIR', '')
LOG_LEVEL = os.environ.get('DJANGO_LOG_LEVEL', 'INFO').upper()

LOGGING = {
    'version': 1,
    # False so Django's own DEFAULT_LOGGING entries survive — notably the
    # 'django.security.DisallowedHost' logger it points at a null handler,
    # which is what keeps bot traffic probing Host headers from filling the
    # log with tracebacks that aren't bugs.
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        # Note the absence of a filter: this is the whole fix.
        'stderr': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'level': 'DEBUG',
        },
    },
    'loggers': {
        # Unhandled exceptions land here: DRF re-raises anything its handler
        # doesn't recognise, and Django's exception handler logs it to
        # 'django.request' with exc_info before returning the 500.
        'django.request': {
            'handlers': ['stderr'],
            'level': 'ERROR',
            # Without this the record also reaches 'django' and its inherited
            # mail_admins handler, double-reporting once ADMINS is ever set.
            'propagate': False,
        },
        'django.security': {
            'handlers': ['stderr'],
            'level': 'ERROR',
            'propagate': False,
        },
        'core': {
            'handlers': ['stderr'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}

if LOG_DIR:
    Path(LOG_DIR).mkdir(parents=True, exist_ok=True)
    LOGGING['handlers']['file'] = {
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': str(Path(LOG_DIR) / 'toponymia.log'),
        'formatter': 'verbose',
        'level': 'DEBUG',
        # 50 MB ceiling, total. Bounded on purpose; see above.
        'maxBytes': 10 * 1024 * 1024,
        'backupCount': 4,
    }
    for _logger in LOGGING['loggers'].values():
        _logger['handlers'].append('file')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # collectstatic target (admin assets)

# WhiteNoise serves the Vite build at the site root. Everything under
# /assets/ is content-hashed by Vite, so browsers may cache it forever.
WHITENOISE_ROOT = WEB_DIST


def immutable_file_test(path, url):
    return url.startswith('/assets/')


WHITENOISE_IMMUTABLE_FILE_TEST = immutable_file_test


# Content-Security-Policy. Today XSS is closed off entirely by how
# react-markdown is configured (no rehype-raw). This is the second layer, so
# that a future mistake there is contained instead of fatal.
#
# The external origins are exactly the two the client talks to; both are in
# the client source, so if either moves, this list has to move with it:
#   tiles.openfreemap.org   basemap tiles, sprites, glyphs (web/src/map/MapView.tsx)
#   photon.komoot.io        geocoding search             (web/src/api.ts)
OPENFREEMAP = 'https://tiles.openfreemap.org'
PHOTON = 'https://photon.komoot.io'

SECURE_CSP = {
    'default-src': [CSP.SELF],
    'base-uri': [CSP.SELF],
    'object-src': [CSP.NONE],
    'frame-ancestors': [CSP.NONE],
    'form-action': [CSP.SELF],
    # The one inline script is index.html's dark-mode anti-flash snippet,
    # which core/spa.py stamps with this nonce as it renders the shell.
    # Without the nonce that script is blocked and returning dark-mode
    # readers get a white flash — silently, since nothing else depends on it.
    # 'wasm-unsafe-eval' is for the RTL text shaper, which is WebAssembly:
    # script-src governs WASM compilation, and without this Arabic and Hebrew
    # labels don't render at all (the failure is a console error, nothing
    # more). It permits WebAssembly only — not eval() — which is the whole
    # reason CSP3 split it out from 'unsafe-eval'.
    'script-src': [CSP.SELF, CSP.WASM_UNSAFE_EVAL, CSP.NONCE],
    # Needed for `style` attributes, not stylesheets: FeaturePicker positions
    # itself with one, and the sheet sets its height the same way. Narrow
    # risk (style injection only), and CSP3's style-src-attr isn't portable
    # enough yet to be more precise.
    'style-src': [CSP.SELF, CSP.UNSAFE_INLINE],
    # MapLibre decodes tiles in workers it creates from blob: URLs, and
    # draws raster/sprite images from the tile host. child-src is the
    # pre-CSP3 spelling of worker-src, kept for older browsers.
    'worker-src': [CSP.SELF, 'blob:'],
    'child-src': [CSP.SELF, 'blob:'],
    'img-src': [CSP.SELF, 'data:', 'blob:', OPENFREEMAP],
    'connect-src': [CSP.SELF, OPENFREEMAP, PHOTON],
    # Both faces are self-hosted under /fonts/; map glyphs are .pbf fetched
    # by XHR, so they fall under connect-src rather than here.
    'font-src': [CSP.SELF],
    'manifest-src': [CSP.SELF],
}


# Production hardening — active whenever DEBUG is off. TLS terminates at
# the reverse proxy (Caddy/nginx), which must send X-Forwarded-Proto;
# HSTS is left to the proxy config.
if not DEBUG:
    if SECRET_KEY.startswith('django-insecure-'):
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY must be set when DEBUG is off. '
            '(DEBUG is off by default; set DJANGO_DEBUG=1 for development.)'
        )
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
