"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# The Vite build Django serves in production: core/spa.py renders
# index.html (injecting per-place SEO meta), WhiteNoise serves the rest.
WEB_DIST = Path(os.environ.get('DJANGO_WEB_DIST', BASE_DIR.parent / 'web' / 'dist'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-dev-only-vp2m4vt^1nq(u+kj#f&yl@8s!z0hw6r$3xebc9do7ga5i_',
)

# SECURITY WARNING: don't run with debug turned on in production!
#
# This defaults to OFF so that a forgotten variable in production fails safe:
# an unset DJANGO_DEBUG gives a hardened server, not tracebacks-with-settings
# on every error page. It also keeps the SECRET_KEY guard below live, since
# that guard only runs when DEBUG is off — with a permissive default, one
# forgotten variable disabled both protections at once.
#
# Development doesn't need to set anything: manage.py (the dev entry point)
# defaults it to '1'. gunicorn imports config.wsgi and never runs manage.py,
# so production keeps the safe default unless it opts in explicitly.
DEBUG = os.environ.get('DJANGO_DEBUG', '0') == '1'

ALLOWED_HOSTS = [
    h for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h
]

# The Vite dev/preview proxy forwards to :8000 with the browser's Origin
# intact, so those origins must be trusted for CSRF checks in dev.
CSRF_TRUSTED_ORIGINS = [
    o
    for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if o
]
if DEBUG:
    CSRF_TRUSTED_ORIGINS += [
        'http://localhost:5173',
        'http://localhost:4173',
    ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'rest_framework',
    'allauth',
    'allauth.account',
    'allauth.headless',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Defaults match the PostGIS service in docker-compose.yml.
# GeoDjango needs system GDAL/GEOS (dnf: gdal geos, apt: gdal-bin libgdal-dev
# libgeos-dev).
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ.get('POSTGRES_DB', 'toponymia'),
        'USER': os.environ.get('POSTGRES_USER', 'toponymia'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'toponymia'),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Authentication — django-allauth in headless-only mode: the React SPA
# talks JSON to /_allauth/browser/v1/* using the session cookie.

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Email is required and must be verified before an account is usable — the
# anti-spam floor, since re-registration is otherwise free and instant.
# Verification is by short code (not a link): allauth emails a code and the
# headless signup flow stays pending until the SPA posts it back, so there is
# no email-link route to catch and the user never leaves the signup form.
# Log in with either identifier, from one field. Email is what people
# actually remember, so this removes "I forgot my username" as a way to lose
# access — but username keeps working, which is the point: with no
# account-settings page yet there is no way to change your address, so email
# must not be the *only* key to the account. The username is the public
# identity regardless (bylines, talk, history), so signup collects both.
# allauth wants exactly one of its credential keys posted, so the SPA picks by
# looking for an "@" — see ACCOUNT_USERNAME_VALIDATORS below, which is what
# makes that test unambiguous.
# Custom adapter enforces the registration blocklist: a banned account's email
# addresses are recorded in BannedEmail, and this refuses a signup that reuses
# one (see core/adapter.py, core.moderation.block_user_emails).
ACCOUNT_ADAPTER = 'core.adapter.AccountAdapter'
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_USERNAME_VALIDATORS = 'core.validators.username_validators'
ACCOUNT_SIGNUP_FIELDS = ['username*', 'email*', 'password1*']
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_VERIFICATION_BY_CODE_ENABLED = True
ACCOUNT_UNIQUE_EMAIL = True
HEADLESS_ONLY = True
HEADLESS_CLIENTS = ('browser',)

# Password reset by code, for the same reason signup verification is: no
# email-link route to catch, so the whole flow stays inside the auth form and
# needs no SPA route of its own. Login stays username-only while there is no
# account-settings page — losing access to your email must cost you the reset
# path, not the account. allauth's 3-minute default is far too tight for an
# email round trip; 15 minutes is still short enough to bound a leaked code.
ACCOUNT_PASSWORD_RESET_BY_CODE_ENABLED = True
ACCOUNT_PASSWORD_RESET_BY_CODE_TIMEOUT = 15 * 60

# Required by the enumeration-resistant reset path, and *only* by it: a reset
# requested for an address with no account still sends mail ("someone asked to
# reset a password here; you have no account") so the response can't be told
# apart from the real one, and that mail links to signup. HEADLESS_ONLY raises
# ImproperlyConfigured rather than defaulting, so without this the request 500s
# — on typo'd addresses only, which is exactly the case no one tests by hand.
# Signup is a header popover, not a route, so the site root is the honest
# target; relative URLs are made absolute against the request.
HEADLESS_FRONTEND_URLS = {'account_signup': '/'}


# Email — verification and password-reset codes. Dev defaults to the
# console backend so signup works with no SMTP configured (the code prints to
# the runserver console); production points DJANGO_EMAIL_BACKEND at SMTP and
# fills host/credentials from the environment. Plain SMTP, no transactional
# API key — keeps to the project's keyless rule.
EMAIL_BACKEND = os.environ.get(
    'DJANGO_EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.environ.get('DJANGO_EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.environ.get('DJANGO_EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('DJANGO_EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('DJANGO_EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('DJANGO_EMAIL_USE_TLS', '1') == '1'
DEFAULT_FROM_EMAIL = os.environ.get(
    'DJANGO_DEFAULT_FROM_EMAIL', 'Toponymia <noreply@toponymia.org>'
)


# Signup rate limit — the anti-spam floor alongside mandatory verification.
# allauth's limits are transient and cache-keyed by IP, so *no IP is stored*
# and there is no privacy-policy burden. Its generous defaults already cover
# login, password reset, and code confirmation; we only tighten signup
# (default 20/min/IP) to 10/min/IP — enough to hobble scripted
# mass-registration from one address, generous enough never to bother a real
# user (even a shared campus/office NAT). One rate only: allauth keys the
# limit on action+scope with no duration in the key, so two same-scope rates
# (e.g. a second '/h/ip') would share one bucket and miscount — its own
# defaults only ever combine *different* scopes (ip + key).
ACCOUNT_RATE_LIMITS = {
    'signup': '10/m/ip',
}

# Behind the M11 reverse proxy every request's REMOTE_ADDR is the proxy's own
# IP, which would collapse all users into a single rate-limit bucket. allauth
# recovers the real client IP from X-Forwarded-For by *counting* trusted hops
# (not by trusting the header, which a client can spoof to rotate IPs), so set
# this to the number of proxies in front of Django in production. 0 in dev
# means REMOTE_ADDR is used directly.
ALLAUTH_TRUSTED_PROXY_COUNT = int(
    os.environ.get('DJANGO_TRUSTED_PROXY_COUNT', '0')
)


# DRF — simple rate limits on anonymous-facing / expensive endpoints
#. UserRateThrottle keys by user id when logged in, client
# IP otherwise, so the per-endpoint scopes below cover both. The default
# cache (LocMemCache) is per-process — fine for a single-VPS v1; a shared
# cache (Redis) is the upgrade if we ever run multiple workers.
REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '120/min',
        'user': '600/min',
        'resolve': '30/min',
        'write': '40/min',
        'report': '15/min',
        'talk': '40/min',
    },
}

# Request-body ceiling, stated explicitly rather than inherited. This is the
# outer backstop behind core.serializers' per-field limits: a fully maxed-out
# article snapshot (20 names x 10k etymology + 30 references each, plus
# derivations and see_also) is roughly 900 kB of text, so 2.5 MB leaves room
# for JSON escaping and multi-byte UTF-8 while still bounding what an
# oversized request can force the server to buffer and parse.
DATA_UPLOAD_MAX_MEMORY_SIZE = 2_621_440  # 2.5 MB


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # collectstatic target (admin assets)

# WhiteNoise serves the Vite build at the site root. Everything under
# /assets/ is content-hashed by Vite, so browsers may cache it forever.
WHITENOISE_ROOT = WEB_DIST


def immutable_file_test(path, url):
    return url.startswith('/assets/')


WHITENOISE_IMMUTABLE_FILE_TEST = immutable_file_test


# Production hardening — active whenever DEBUG is off. TLS terminates at
# the reverse proxy (Caddy/nginx), which must send X-Forwarded-Proto;
# HSTS is left to the proxy config.
if not DEBUG:
    if SECRET_KEY.startswith('django-insecure-'):
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY must be set when DEBUG is off. '
            '(DEBUG is off by default; set DJANGO_DEBUG=1 for development.)'
        )
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
